const Menu = [
    {
        id: 1,
        image: "images/noodles.png",
        name: "maggi",
        category: "breakfast",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 2,
        image: "images/ice-cream.png",
        name: "Ice-Creame",
        category: "evening",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 3,
        image: "images/fried-spring-rolls.png",
        name: "Spring rolls",
        category: "lunch",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 4,
        image: "images/dosa.png",
        name: "Dhosha",
        category: "dinner",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 5,
        image: "images/latte-art.png",
        name: "Coffee",
        category: "evening",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 6,
        image: "images/samosa.png",
        name: "Samosa",
        category: "breakfast",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 7,
        image: "images/sandwich.png",
        name: "Sandwich",
        category: "evening",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 8,
        image: "images/pizza.png",
        name: "Pizaa",
        category: "dinner",
        price: "12₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
    {
        id: 9,
        image: "images/Lapsi.jpg",
        name: "Lapsi",
        category: "mayur",
        price: "120₹",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum voluptas facere corrupti voluptatem repellat quasi quo doloremque molestiae tempora nemo atque, eaut? Ratione excepturi odio repudiandae neque unde accusantium!",
    },
];

export default Menu;